Bugfix: add-sample-rate-native
getsentry/sentry-dart pull request #2200
Opened 2024-07-26 12:10 UTC by JulianBissekkou

## :scroll: Description
During development I discovered that the sample rate is not correctly forwarded to the native sdks.

## :bulb: Motivation and Context
This PR makes sure that initialization of the native sdks also uses the configured sampleRate and traceSampleRate from the FlutterSentryOptions.

## :green_heart: How did you test it?
I tested this by setting a breakpoint and ensuring that my configuration was applied to the native options. If there is a better way, let me know :) 

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps

2024-07-26 12:15 UTC, JulianBissekkou commented
I checked "No breaking changes" since I think this is not breaking. However, the sdk might behave differently but I would say its no the correct expected behavior.

2024-07-26 12:16 UTC, buenaflor commented
hey, do you use the native sdk alongside the flutter sdk?

2024-07-26 12:21 UTC, buenaflor commented
I'm trying to find the context as to why this was not added before. It's hard to imagine that this was just an oversight but it could be.

2024-07-26 12:22 UTC, buenaflor commented
Example: our react native SDK also doesn't set the sample rates during init: https://github.com/getsentry/sentry-react-native/blob/979a258538e6b140d912f7d74b89f684c504b67f/android/src/main/java/io/sentry/react/RNSentryModuleImpl.java#L182

2024-07-26 12:27 UTC, JulianBissekkou commented
@buenaflor 
I am only using the flutter sdk and my application is running on android and iOS and I was curious how the implementation of the initialization is done and then I also found that some of the properties where not parsed.

I was also suprised, but my assumption was that nobody found this since most react native and flutter developers are interested in the errors that are thrown in the TS or Dart code and the native exceptions are very rare. 
The missing change in the sampleRate is therefore nothing that most people would directly notice since it doesn't affect many events.

I wasn't sure if there is some kind of magic initialization that I was missing so take your time with reviewing this. 
Looking forward hearing from you :)

2024-07-29 10:38 UTC, buenaflor commented
After some discussion I don't think this should be added since there's the possibility of double instrumentation since the native sdks themselves have instrumentation for certain integrations. For example the cocoa sdk has all these [automatic instrumentation](https://docs.sentry.io/platforms/apple/guides/ios/tracing/instrumentation/automatic-instrumentation/)  which might result in duplicate data being sent. 

In terms of feature set and design we also want to keep our hybrid sdks as consistent as possible to one another.

So adding this change brings a lot of implications and is actually a rather big decision.

2024-07-30 08:23 UTC, JulianBissekkou commented
@buenaflor 
Can you explain why we get duplicate instrumentation? We are only updating configuration parameters of the iOS sdks. This can also be done by developers that are using the native iOS integration. The flutter/dart sdk will only provide data to sentry for the dart specific part.

2024-07-30 09:45 UTC, buenaflor commented
@JulianBissekkou if we pass `tracesSampleRate` as well then we would get duplicate appstart instrumentations, one implemented in native ios/android and one implemented in flutter. Just one of many examples.

here is what we should do: I agree that `sampleRate` should be passed, this controls errors and crashes so it makes sense to pass it. but `tracesSampleRate` should stay as it is because of the mentioned reason.

2024-07-30 09:52 UTC, buenaflor commented on flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutter.kt
> +    }
```suggestion
```

2024-07-30 09:52 UTC, buenaflor commented on flutter/lib/src/native/sentry_native_channel.dart
> +      'tracesSampleRate': options.tracesSampleRate,
```suggestion
```

2024-07-30 09:52 UTC, buenaflor commented on flutter/ios/Classes/SentryFlutter.swift
> +        }
```suggestion
```

2024-07-31 06:11 UTC, JulianBissekkou commented
@buenaflor Thanks for explaining.
I applied your suggestions 👍🏽

2024-08-01 08:24 UTC, buenaflor commented
@JulianBissekkou some tests are failing since but it should be a very simple fix

also could you add this changelog entry under `# Fixes` in the unreleased section

```
- Pass `sampleRate` to native SDKs ([#2200](https://github.com/getsentry/sentry-dart/pull/2200))
```

2024-08-12 12:37 UTC, denrase requested changes
Thank you for contributing! 

- [ ] Please also add tests for the new values our native tests `SentryFlutterTests.swift` and `SentryFlutterTest.kt`.
- [ ] Update the test expectations in `init_native_sdk_test.dart` to include the new value

2024-08-12 12:44 UTC, JulianBissekkou commented
I will make this PR ready later this week :) Thanks for your feedback

2024-09-23 11:43 UTC, denrase approved these changes
LGTM, only issue left is a linting issue in the Kotlin file:

```
SentryFlutterTest.kt:162:28: error: Missing trailing comma before ")"
```

2024-12-02 07:04 UTC, JulianBissekkou commented
Closing as other PRs have already implemented that feature.

2024-12-02 07:04 UTC, closed without merging