Add port to support the server doesn't using 80
getsentry/sentry-dart pull request #39
Opened 2019-02-27 10:02 UTC by ZhihuiTian

2019-07-24 07:41 UTC, phpmaple commented
approved?

2019-09-11 22:16 UTC, yjbanov requested changes
Thank you for the PR and sorry for the delay. This looks like a good feature.

Can you please add tests for this?

2019-09-11 22:16 UTC, yjbanov commented on lib/sentry.dart
> +      '${dsnUri.scheme}://${dsnUri.host}${dsnUri.port != 80 && dsnUri.port != 443 ? ':' + dsnUri.port.toString() : ''}/api/$projectId/store/';
This is probably a good time to switch from the `=>` shorthand to a `{ }` block syntax, and make port a variable.

2019-09-11 22:16 UTC, yjbanov commented on lib/sentry.dart
> +      '${dsnUri.scheme}://${dsnUri.host}${dsnUri.port != 80 && dsnUri.port != 443 ? ':' + dsnUri.port.toString() : ''}/api/$projectId/store/';
`':' + dsnUri.port.toString()` can be replaced with `':${dsnUri.port}'`

2019-09-18 14:55 UTC, MrMoronIV commented
Can this be pulled into master? 

My SDN: 
```
https://dc31d4db460d4c198241b52537d90bc6:a08b9b9454e64dbea2a349d95cb5ba59@err.domain.com:9500/6
```
After a while I get:
```
Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = err.domain.com, port = 50563
```
I tried again:
```
Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = err.domain.com, port = 50564
```

without defining a port it says: `port = 50566`

2019-10-15 14:33 UTC, yjbanov commented
It seems https://github.com/flutter/sentry/pull/42 covers this feature, as well as adds support for custom paths. So I'll close this PR in favor of https://github.com/flutter/sentry/pull/42.

2019-10-15 14:33 UTC, closed without merging