Add 'transaction', 'contexts' and 'breadcrumbs' in event
getsentry/sentry-dart pull request #43
Opened 2019-09-02 10:24 UTC by yrom

ref docs:
transaction: https://docs.sentry.io/development/sdk-dev/event-payloads/#optional-attributes
contexts: https://docs.sentry.io/development/sdk-dev/event-payloads/contexts/
breadcrumbs: https://docs.sentry.io/development/sdk-dev/event-payloads/breadcrumbs/

There is a related pr #40 when i create this pr. In my opinion, the `Event` class should know nothing about what the `contexts` have, so i did not create the wrapper class for the `os`,`device`,etc which it might contains.

2019-09-06 15:17 UTC, SammyO commented
+1 to get this merged

2019-09-25 17:07 UTC, yjbanov requested changes
Transaction and breadcrumbs LGTM. Let's leave contexts out of this PR. https://github.com/flutter/sentry/pull/40 is adding a fully schemed version of it.

2019-09-26 05:46 UTC, yrom commented
@yjbanov Tthe 'contexts' was discarded.

2019-09-26 16:29 UTC, yjbanov commented on lib/sentry.dart
> +  /// see docs https://docs.sentry.io/development/sdk-dev/event-payloads/breadcrumbs/#breadcrumb-types
Let's reformat this a bit:

```
/// Describes what type of breadcrumb this is.
///
/// Possible values: "default", "http", "navigation".
///
/// See also:
///
/// * https://docs.sentry.io/development/sdk-dev/event-payloads/breadcrumbs/#breadcrumb-types
```

2019-09-26 16:29 UTC, yjbanov commented on lib/sentry.dart
> +      'timestamp': timestamp.millisecondsSinceEpoch ~/ 1000,
Let's reuse https://github.com/flutter/sentry/blob/e14f1497d623ae29ca35d4cff5858fb540b83352/lib/src/utils.dart#L29

2019-09-26 16:29 UTC, yjbanov commented on lib/sentry.dart
> +  /// note: serialized in  seconds
Some clean-up:

```
/// The time the breadcrumb was recorded.
///
/// The value is submitted to Sentry with second precision.
```

2019-09-26 16:29 UTC, yjbanov commented
Thanks, just a couple more things I noticed.

2019-09-26 16:31 UTC, yjbanov commented on lib/sentry.dart
> +  /// for e.g., might be the route name: `"/users/<username>/"`.
nit: either "for example", or "e.g.", but not both :)
nit: no need for "might be", as we already say "for example"

2019-09-26 16:31 UTC, yjbanov commented on lib/sentry.dart
> +  /// see docs https://docs.sentry.io/enriching-error-data/breadcrumbs/?platform=javascript
For consistency, let's format as:

```
/// See also:
/// * https://docs.sentry.io/enriching-error-data/breadcrumbs/?platform=javascript
```

2019-09-27 03:28 UTC, yrom commented
@yjbanov Thanks for reviewing. Request changes applied.

2019-09-27 20:20 UTC, yjbanov commented
@yrom Curious, why did you decide to rollback the timestamp in https://github.com/flutter/sentry/pull/43/commits/cd6939226ef0da823e49aee9a55f58c1353e2eb9?

2019-09-28 01:24 UTC, yrom commented
@yjbanov Looked up the `sentry-java` SDK.
See  https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java#L299. 
They were using timestamp. 😅

2019-10-01 13:39 UTC, jaumard commented
Would love to have this and "Context" merged, as currently reporting is quite light :)

2019-10-01 22:17 UTC, yjbanov commented
> @yjbanov Looked up the `sentry-java` SDK.
> See https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java#L299.
> They were using timestamp.

Would you mind trying `formatDateAsIso8601WithSecondPrecision` instead? This way we'd consistently use the same date-time formatting throughout the client.

2019-10-08 03:57 UTC, yrom commented
@yjbanov Sorrry for my late reply. I have updated the commits, again.

2019-10-15 14:39 UTC, yjbanov commented
LGTM! Thank you for contributing this feature!

2019-10-15 14:40 UTC, merged